//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentElection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ElectionVote
    {
        public int id { get; set; }
        public Nullable<int> ElectionId { get; set; }
        public Nullable<int> CandidatId { get; set; }
        public Nullable<int> StudentRollNumber { get; set; }
    
        public virtual Election Election { get; set; }
        public virtual ElectionCandidate ElectionCandidate { get; set; }
        public virtual Student Student { get; set; }
    }
}
