//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentElection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.ElectionVotes = new HashSet<ElectionVote>();
        }
    
        public int rollno { get; set; }
        public string studentname { get; set; }
        public System.DateTime DOB { get; set; }
        public string branch { get; set; }
        public System.DateTime yearofjoining { get; set; }
        public int mobilenumber { get; set; }
        public int password { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ElectionVote> ElectionVotes { get; set; }
    }
}
